-- Команда (пара) строго в рамках одного турнира; пары между турнирами не переиспользуем.
create table if not exists tournament.teams (
  id bigint generated by default as identity primary key,
  tournament_id bigint not null
    references tournament.tournaments (id) on delete cascade,
  player_1_id bigint not null
    references tournament.players (id) on delete restrict,
  player_2_id bigint not null
    references tournament.players (id) on delete restrict,
  sort_index integer not null default 0,
  created_at timestamptz not null default now(),
  constraint teams_distinct_players check (player_1_id <> player_2_id)
);

create index if not exists teams_tournament_id_idx on tournament.teams (tournament_id);
create index if not exists teams_tournament_sort_idx on tournament.teams (tournament_id, sort_index);

-- Одна и та же пара (в любом порядке p1/p2) — одна строка
create unique index if not exists teams_tournament_pair_unique
  on tournament.teams (tournament_id, least(player_1_id, player_2_id), greatest(player_1_id, player_2_id));

comment on table tournament.teams is 'Пара/команда только для одного tournament_id; состав между турнирами не храним.';

alter table tournament.teams enable row level security;

drop policy if exists "teams_all_anon" on tournament.teams;
create policy "teams_all_anon" on tournament.teams
  for all
  to anon, authenticated
  using (true)
  with check (true);
